name: Java Testing

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Compile Code
      run: javac -cp .:lib/junit-4.13.2.jar -d out src/TaxGPT.java test/TaxGPTTest.java

    - name: Run Tests
      run: java -cp out:lib/junit-4.13.2.jar org.junit.runner.JUnitCore TaxGPTTest
